"""feat: sustainability attribute association table

Revision ID: 3deb5ff56b17
Revises: 7475c9a40243
Create Date: 2025-04-17 21:52:40.547837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3deb5ff56b17'
down_revision = '7475c9a40243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sustainability_association',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sustainability_attribute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sustainability_attribute_id'], ['sustainability_attributes.id'], )
    )
    op.drop_table('product_sustainability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sustainability',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certification_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['sustainability_attributes.id'], name='product_sustainability_attribute_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_sustainability_product_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'attribute_id', 'id', name='product_sustainability_pkey')
    )
    op.drop_table('product_sustainability_association')
    # ### end Alembic commands ###
