"""removed model for producttag mapping. added new table

Revision ID: 7475c9a40243
Revises: 97ad1530a22d
Create Date: 2025-04-17 21:37:18.789763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7475c9a40243'
down_revision = '97ad1530a22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tag_association',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['product_tags.id'], )
    )
    op.drop_table('product_tag_mapping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tag_mapping',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_tag_mapping_product_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['product_tags.id'], name='product_tag_mapping_tag_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'tag_id', 'id', name='product_tag_mapping_pkey')
    )
    op.drop_table('product_tag_association')
    # ### end Alembic commands ###
